### PR TITLE
Treat unsuccessful API responses as errors

### LINKED ISSUE #32: Error flow not working as expected
Thanks for providing a formal Node.js Client library for Google Maps Services 👍 

But, I ended up wasting many hours to find out why my geocoding API calls stopped working suddenly with no error :-(

Investigating into it, found that instead of an error, the response had this:

> { error_message: 'Browser API keys cannot have referer restrictions when used with this API.',
>   results: [],
>   status: 'REQUEST_DENIED' }

Given there is an error(err) object in the callback function, shouldn't that be set as well for proper error handling instead of sticking the error message just to the response object?

``` javascript
// Geocode an address.
googleMapsClient.geocode({
  address: '1600 Amphitheatre Parkway, Mountain View, CA'
}, function(err, response) {
  if (!err) {
    console.log(response.json.results);
  }
});
```

### PR DESCRIPTION
**Pull request by stephenfarrar**
Note: this is a breaking change to the library.

Fixes #32

### CODE REVIEW

File: docs/interfaces.js [hunk 1]
```diff
@@ -31,18 +31,27 @@
...
  * <pre>
  *   googleMapsClient.geocode({...}, function(err, response) {
- *     if (err) {
- *       // Handle error.
- *     } else {
+ *     if (!err) {
  *       // Handle response.
+ *     } else if (err === 'timeout') {
+ *       // Handle timeout.
+ *     } else if (err.json) {
```
Comment (migueloller) [inline docs/interfaces.js]: If `err` is an instance of `Response`, do we expect `err.json` to always be true since it would be [a function that returns a promise](https://developer.mozilla.org/en-US/docs/Web/API/Response)? Or is it not the JavaScript `Response` (and perhaps a `Response` from another library) ?

Comment (stephenfarrar) [inline docs/interfaces.js]: I've renamed `Response` to `ClientResponse` to make this clearer.

But, yes, if err is a `ClientResponse` then `err.json` will always be truthy (and it will contain the `status` from the maps API).

**Comment by migueloller** [comment]
This looks great @stephenfarrar!
